from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ..entities import Agent, MemoryItem
from .conflict_schema import (
    ConflictCheckResult,
    ConflictType,
)


@dataclass
class MemoryWriteResult:
    """
    Result of controlled private memory writing.

    candidate_memory_id:
        Temporary candidate ID used during conflict checking.

    stored_memory_id:
        Actual ID generated by MemoryService after persistence.
    """

    success: bool
    candidate_memory_id: str
    stored_memory_id: Optional[str]
    written: bool
    should_promote: bool
    requires_review: bool
    conflict_type: str
    message: str


class MemoryWriteController:
    """
    Controlled private-memory writing layer.

    Responsibilities:
    - enforce conflict decisions
    - prevent direct worker writes to shared memory
    - call MemoryService using its actual business interface
    - preserve permission checks and operation logging

    This class does not:
    - build candidate memories
    - detect conflicts
    - approve promotions
    """

    def __init__(
        self,
        *,
        memory_service,
    ) -> None:
        self.memory_service = memory_service

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def write_candidate_memory(
        self,
        *,
        candidate_memory: MemoryItem,
        requesting_agent: Agent,
        conflict_result: ConflictCheckResult,
    ) -> MemoryWriteResult:
        """
        Write a candidate according to the conflict decision.

        Policies:
        - duplicate:
            do not write and do not promote
        - conflicting answer:
            write privately for review, but do not promote
        - no conflict:
            write privately and allow promotion
        - outdated:
            write privately, but require review
        """

        candidate_memory_id = self._get_memory_id(candidate_memory)

        self._validate_conflict_result(
            candidate_memory_id=candidate_memory_id,
            conflict_result=conflict_result,
        )

        if not conflict_result.should_write:
            return MemoryWriteResult(
                success=True,
                candidate_memory_id=candidate_memory_id,
                stored_memory_id=None,
                written=False,
                should_promote=False,
                requires_review=conflict_result.requires_review,
                conflict_type=conflict_result.conflict_type.value,
                message=(
                    "Candidate memory was not written because the conflict "
                    f"policy blocked writing: {conflict_result.message}"
                ),
            )

        # These policy errors should remain visible rather than being converted
        # into a generic unsuccessful result.
        self._assert_private_memory(candidate_memory)
        self._assert_agent_owns_candidate(
            candidate_memory=candidate_memory,
            requesting_agent=requesting_agent,
        )

        try:
            stored_memory = self._write_private_memory(
                candidate_memory=candidate_memory,
                requesting_agent=requesting_agent,
                conflict_result=conflict_result,
            )

            return MemoryWriteResult(
                success=True,
                candidate_memory_id=candidate_memory_id,
                stored_memory_id=stored_memory.memory_id,
                written=True,
                should_promote=conflict_result.should_promote,
                requires_review=conflict_result.requires_review,
                conflict_type=conflict_result.conflict_type.value,
                message=self._build_success_message(conflict_result),
            )

        except Exception as error:
            return MemoryWriteResult(
                success=False,
                candidate_memory_id=candidate_memory_id,
                stored_memory_id=None,
                written=False,
                should_promote=False,
                requires_review=True,
                conflict_type=conflict_result.conflict_type.value,
                message=(
                    f"Failed to write candidate memory through "
                    f"MemoryService.create_private_memory(): {error}"
                ),
            )

    def write_without_conflict(
        self,
        *,
        candidate_memory: MemoryItem,
        requesting_agent: Agent,
    ) -> MemoryWriteResult:
        """
        Convenience method mainly for isolated tests.
        """

        conflict_result = ConflictCheckResult.no_conflict(
            candidate_memory_id=self._get_memory_id(candidate_memory),
            message="Candidate was treated as having no conflict.",
        )

        return self.write_candidate_memory(
            candidate_memory=candidate_memory,
            requesting_agent=requesting_agent,
            conflict_result=conflict_result,
        )

    # ------------------------------------------------------------------
    # Actual MemoryService integration
    # ------------------------------------------------------------------

    def _write_private_memory(
        self,
        *,
        candidate_memory: MemoryItem,
        requesting_agent: Agent,
        conflict_result: ConflictCheckResult,
    ) -> MemoryItem:
        """
        Call the actual MemoryService.create_private_memory interface.

        MemoryService creates a new MemoryItem and therefore generates the
        persistent memory ID itself. The candidate ID remains an audit and
        conflict-check identifier.
        """

        metadata = candidate_memory.metadata

        create_kwargs = {
            "agent": requesting_agent,
            "content": candidate_memory.content,
            "summary": getattr(candidate_memory, "summary", None),
            "memory_type": metadata.memory_type,
            "tags": list(metadata.tags),
            "importance": metadata.importance,
            "confidence": metadata.confidence,
            "source_task_id": metadata.source_task_id,
            "source_message_ids": list(metadata.source_message_ids),
            "reason": self._build_write_reason(conflict_result),
        }

        source_type = getattr(metadata, "source_type", None)

        if source_type is not None:
            create_kwargs["source_type"] = source_type

        stored_memory = self.memory_service.create_private_memory(
            **create_kwargs
        )

        if not isinstance(stored_memory, MemoryItem):
            raise TypeError(
                "MemoryService.create_private_memory() did not return "
                f"a MemoryItem. Got {type(stored_memory)!r}."
            )

        return stored_memory

    # ------------------------------------------------------------------
    # Validation and policy
    # ------------------------------------------------------------------

    @staticmethod
    def _validate_conflict_result(
        *,
        candidate_memory_id: str,
        conflict_result: ConflictCheckResult,
    ) -> None:
        """
        Ensure the conflict result belongs to this candidate.
        """

        if conflict_result.candidate_memory_id != candidate_memory_id:
            raise ValueError(
                "Conflict result candidate ID does not match the candidate "
                f"memory: {conflict_result.candidate_memory_id!r} != "
                f"{candidate_memory_id!r}."
            )

    @staticmethod
    def _assert_private_memory(
        memory_item: MemoryItem,
    ) -> None:
        """
        Workers must not write candidate memories directly as shared memory.
        """

        scope = MemoryWriteController._get_memory_scope(memory_item)

        if scope != "private":
            raise ValueError(
                "Candidate memory must be private before controlled writing. "
                f"Got scope={scope!r}."
            )

    @staticmethod
    def _assert_agent_owns_candidate(
        *,
        candidate_memory: MemoryItem,
        requesting_agent: Agent,
    ) -> None:
        """
        Ensure a worker writes only its own candidate memory.

        MemoryService will perform its own permission check as well.
        """

        owner_agent_id = candidate_memory.metadata.owner_agent_id

        if owner_agent_id != requesting_agent.agent_id:
            raise ValueError(
                "Requesting agent does not own the candidate memory. "
                f"owner={owner_agent_id!r}, "
                f"requesting_agent={requesting_agent.agent_id!r}."
            )

    @staticmethod
    def _build_write_reason(
        conflict_result: ConflictCheckResult,
    ) -> str:
        if conflict_result.conflict_type == ConflictType.NONE:
            return (
                "Candidate QA memory written privately after successful "
                "conflict check."
            )

        if (
            conflict_result.conflict_type
            == ConflictType.CONFLICTING_ANSWER
        ):
            return (
                "Conflicting QA memory preserved privately for review; "
                "automatic promotion is blocked."
            )

        if conflict_result.conflict_type == ConflictType.OUTDATED:
            return (
                "Potentially outdated memory preserved privately for review."
            )

        return (
            "Candidate memory written according to conflict policy: "
            f"{conflict_result.conflict_type.value}."
        )

    @staticmethod
    def _build_success_message(
        conflict_result: ConflictCheckResult,
    ) -> str:
        if conflict_result.conflict_type == ConflictType.NONE:
            return (
                "Candidate memory was written as private memory and is "
                "eligible for promotion."
            )

        if (
            conflict_result.conflict_type
            == ConflictType.CONFLICTING_ANSWER
        ):
            return (
                "Candidate memory was written privately for review, but "
                "automatic promotion is blocked."
            )

        if conflict_result.conflict_type == ConflictType.OUTDATED:
            return (
                "Candidate memory was written privately and requires review "
                "before promotion."
            )

        return (
            "Candidate memory was written according to conflict policy."
        )

    # ------------------------------------------------------------------
    # Field helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _get_memory_id(
        memory_item: MemoryItem,
    ) -> str:
        memory_id = getattr(memory_item, "memory_id", None)

        if not memory_id:
            raise AttributeError(
                "MemoryItem must contain a non-empty memory_id."
            )

        return str(memory_id)

    @staticmethod
    def _get_memory_scope(
        memory_item: MemoryItem,
    ) -> str:
        value = memory_item.metadata.scope

        if hasattr(value, "value"):
            value = value.value

        return str(value).strip().lower()