from __future__ import annotations

"""
LangGraph state for the generic runtime memory-access request subgraph.

The state contains only per-run, JSON-serialisable workflow data. Runtime
dependencies such as Coordinators, Critics, Gateways, Services, Stores, and
LLM clients belong in ``AccessRequestDependencies`` rather than in this state.
"""

from collections.abc import Mapping, Sequence
from operator import add
from typing import (
    Annotated,
    Any,
    Final,
    Literal,
    TypedDict,
)


AccessRequestWorkflowStatus = Literal[
    "initialised",
    "validated",
    "access_checked",
    "already_authorised",
    "request_submitted",
    "decision_proposed",
    "review_pending",
    "reviewed",
    "finalised",
    "executed",
    "failed",
]

TERMINAL_ACCESS_REQUEST_STATUSES: Final[
    frozenset[str]
] = frozenset(
    {
        "already_authorised",
        "executed",
        "failed",
    }
)


class AccessRequestState(
    TypedDict,
    total=False,
):
    """
    Shared state carried by one runtime access-request subgraph execution.

    Structured Pydantic outputs and Gateway DTOs are stored as
    ``model_dump(mode="json")`` dictionaries. This keeps the state compatible
    with LangGraph checkpointing and ordinary JSON serialisation.
    """

    # ------------------------------------------------------------------
    # Invocation identity
    # ------------------------------------------------------------------

    run_id: str
    status: AccessRequestWorkflowStatus

    # ------------------------------------------------------------------
    # Required request input
    # ------------------------------------------------------------------

    memory_id: str
    owner_agent_id: str
    requester_agent_id: str

    # Governance actors used by MemorySharingGateway.
    coordinator_agent_id: str
    critic_agent_id: str

    # Registered Agents that may appear in this workflow invocation.
    available_agent_ids: list[str]

    request_reason: str
    task_id: str | None

    # ---------------------------------
    # ---------------------------------
    # Generic decision context
    # ------------------------------------------------------------------

    # Safe, serialisable representation of the requested memory.
    memory_context: dict[str, Any]

    # Active access-control and governance constraints.
    policy_context: dict[str, Any]

    # Current task or parent-workflow context.
    task_context: dict[str, Any]

    # Deterministic risk labels supplied by the parent workflow.
    risk_labels: list[str]

    # ------------------------------------------------------------------
    # Existing-access check
    # ------------------------------------------------------------------

    # None before MemorySharingGateway.has_access() is called.
    had_access_before: bool | None

    # True when the workflow terminates because the requester already had
    # permission and no new request was necessary.
    request_skipped: bool

    # ------------------------------------------------------------------
    # Submitted request
    # ------------------------------------------------------------------

    # ID generated by MemorySharingGateway.request_access().
    request_id: str | None

    # Serialised MemoryAccessRequestResult returned at submission time.
    submitted_request: dict[str, Any] | None

    request_submitted: bool

    # ------------------------------------------------------------------
    # Coordinator initial decision
    # ------------------------------------------------------------------

    # Serialised MemoryAccessRequestDecisionOutput.
    initial_decision: dict[str, Any] | None

    # ------------------------------------------------------------------
    # Deterministic review-gate result
    # ------------------------------------------------------------------

    review_required: bool
    review_reason_codes: list[str]
    review_reasons: list[str]
    triggered_risk_labels: list[str]

    # ------------------------------------------------------------------
    # Critic review
    # ------------------------------------------------------------------

    # Serialised MemoryAccessRequestReviewOutput.
    critic_review: dict[str, Any] | None

    # Serialised MemoryAccessRequestResult returned by review_request().
    reviewed_request: dict[str, Any] | None

    review_completed: bool
    review_recorded: bool

    # ------------------------------------------------------------------
    # Coordinator finalisation
    # ------------------------------------------------------------------

    # Serialised final MemoryAccessRequestDecisionOutput. On a no-review path,
    # this may be a copy of ``initial_decision``.
    final_decision: dict[str, Any] | None

    # ------------------------------------------------------------------
    # Gateway decision execution
    # ------------------------------------------------------------------

    # Serialised MemoryAccessDecisionResult returned by approve/reject.
    decision_result: dict[str, Any] | None

    decision_executed: bool
    access_granted: bool

    # Result of an optional post-decision has_access() verification.
    final_access_confirmed: bool | None

    # Stable terminal request values copied from the Gateway DTO.
    final_request_status: str | None
    final_request_decision: str | None

    # ------------------------------------------------------------------
    # Observability and failure handling
    # ------------------------------------------------------------------

    node_trace: Annotated[
        list[str],
        add,
    ]

    warnings: Annotated[
        list[str],
        add,
    ]

    errors: Annotated[
        list[str],
        add,
    ]

    failed_node: str | None
    error_type: str | None
    error_message: str | None


def build_initial_access_request_state(
    *,
    memory_id: str,
    owner_agent_id: str,
    requester_agent_id: str,
    coordinator_agent_id: str,
    critic_agent_id: str,
    available_agent_ids: Sequence[str],
    request_reason: str,
    task_id: str | None = None,
    memory_context: Mapping[str, Any] | None = None,
    policy_context: Mapping[str, Any] | None = None,
    task_context: Mapping[str, Any] | None = None,
    risk_labels: Sequence[str] = (),
    run_id: str | None = None,
) -> AccessRequestState:
    """
    Build a validated initial state for one cross-Agent access request.

    The owner, requester, Coordinator, and Critic must all be registered in
    ``available_agent_ids``. The wildcard ``"*"`` is not a registered Agent
    and is removed from the list.
    """
    clean_memory_id = _required_text(
        memory_id,
        "memory_id",
    )
    clean_owner_id = _required_text(
        owner_agent_id,
        "owner_agent_id",
    )
    clean_requester_id = _required_text(
        requester_agent_id,
        "requester_agent_id",
    )
    clean_coordinator_id = _required_text(
        coordinator_agent_id,
        "coordinator_agent_id",
    )
    clean_critic_id = _required_text(
        critic_agent_id,
        "critic_agent_id",
    )
    clean_request_reason = _required_text(
        request_reason,
        "request_reason",
    )

    clean_available_agent_ids = [
        agent_id
        for agent_id in _clean_string_list(
            available_agent_ids
        )
        if agent_id != "*"
    ]

    if not clean_available_agent_ids:
        raise ValueError(
            "available_agent_ids must contain at least one Agent ID."
        )

    required_agent_ids = {
        "owner_agent_id": clean_owner_id,
        "requester_agent_id": clean_requester_id,
        "coordinator_agent_id": clean_coordinator_id,
        "critic_agent_id": clean_critic_id,
    }

    for field_name, agent_id in required_agent_ids.items():
        if agent_id not in clean_available_agent_ids:
            raise ValueError(
                f"{field_name} must appear in available_agent_ids."
            )

    clean_task_id = _optional_text(
        task_id
    )
    clean_run_id = _optional_text(
        run_id
    )

    return AccessRequestState(
        run_id=(
            clean_run_id
            or (
                f"access:{clean_memory_id}:"
                f"{clean_requester_id}"
            )
        ),
        status="initialised",
        memory_id=clean_memory_id,
        owner_agent_id=clean_owner_id,
        requester_agent_id=(
            clean_requester_id
        ),
        coordinator_agent_id=(
            clean_coordinator_id
        ),
        critic_agent_id=clean_critic_id,
        available_agent_ids=(
            clean_available_agent_ids
        ),
        request_reason=(
            clean_request_reason
        ),
        task_id=clean_task_id,
        memory_context=_clean_context(
            memory_context,
            "memory_context",
        ),
        policy_context=_clean_context(
            policy_context,
            "policy_context",
        ),
        task_context=_clean_context(
            task_context,
            "task_context",
        ),
        risk_labels=_clean_labels(
            risk_labels
        ),
        had_access_before=None,
        request_skipped=False,
        request_id=None,
        submitted_request=None,
        request_submitted=False,
        initial_decision=None,
        review_required=False,
        review_reason_codes=[],
        review_reasons=[],
        triggered_risk_labels=[],
        critic_review=None,
        reviewed_request=None,
        review_completed=False,
        review_recorded=False,
        final_decision=None,
        decision_result=None,
        decision_executed=False,
        access_granted=False,
        final_access_confirmed=None,
        final_request_status=None,
        final_request_decision=None,
        node_trace=[],
        warnings=[],
        errors=[],
        failed_node=None,
        error_type=None,
        error_message=None,
    )


def is_terminal_access_request_status(
    status: str | None,
) -> bool:
    """
    Return whether an access-request workflow status is terminal.
    """
    if status is None:
        return False

    return (
        str(status).strip().lower()
        in TERMINAL_ACCESS_REQUEST_STATUSES
    )


def validate_access_request_identity(
    state: Mapping[str, Any],
) -> None:
    """
    Validate stable identity fields required by access-request nodes.

    Node-specific fields such as ``request_id``, ``initial_decision``, or
    ``critic_review`` are deliberately validated by the node that consumes
    them.
    """
    _required_text(
        state.get("memory_id"),
        "memory_id",
    )

    required_agent_ids = {
        "owner_agent_id": _required_text(
            state.get("owner_agent_id"),
            "owner_agent_id",
        ),
        "requester_agent_id": _required_text(
            state.get(
                "requester_agent_id"
            ),
            "requester_agent_id",
        ),
        "coordinator_agent_id": _required_text(
            state.get(
                "coordinator_agent_id"
            ),
            "coordinator_agent_id",
        ),
        "critic_agent_id": _required_text(
            state.get("critic_agent_id"),
            "critic_agent_id",
        ),
    }

    _required_text(
        state.get("request_reason"),
        "request_reason",
    )

    available_agent_ids = [
        agent_id
        for agent_id in _clean_string_list(
            state.get(
                "available_agent_ids",
                [],
            )
        )
        if agent_id != "*"
    ]

    if not available_agent_ids:
        raise ValueError(
            "available_agent_ids must contain at least one Agent ID."
        )

    for field_name, agent_id in required_agent_ids.items():
        if agent_id not in available_agent_ids:
            raise ValueError(
                f"{field_name} must appear in available_agent_ids."
            )


def _required_text(
    value: Any,
    field_name: str,
) -> str:
    cleaned = str(
        value or ""
    ).strip()

    if not cleaned:
        raise ValueError(
            f"{field_name} cannot be empty."
        )

    return cleaned


def _optional_text(
    value: Any,
) -> str | None:
    if value is None:
        return None

    cleaned = str(value).strip()
    return cleaned or None


def _clean_string_list(
    values: Sequence[Any] | Any,
) -> list[str]:
    if values is None:
        return []

    if isinstance(values, str):
        values = [values]

    try:
        iterator = iter(values)
    except TypeError as error:
        raise ValueError(
            "Expected a sequence of string values."
        ) from error

    result: list[str] = []

    for value in iterator:
        cleaned = str(
            value or ""
        ).strip()

        if (
            cleaned
            and cleaned not in result
        ):
            result.append(cleaned)

    return result


def _clean_labels(
    values: Sequence[Any] | Any,
) -> list[str]:
    result: list[str] = []

    for value in _clean_string_list(
        values
    ):
        label = value.lower()

        if label not in result:
            result.append(label)

    return result


def _clean_context(
    value: Mapping[str, Any] | None,
    field_name: str,
) -> dict[str, Any]:
    if value is None:
        return {}

    if not isinstance(
        value,
        Mapping,
    ):
        raise ValueError(
            f"{field_name} must be a mapping."
        )

    return dict(value)


__all__ = [
    "AccessRequestWorkflowStatus",
    "TERMINAL_ACCESS_REQUEST_STATUSES",
    "AccessRequestState",
    "build_initial_access_request_state",
    "is_terminal_access_request_status",
    "validate_access_request_identity",
]